const galleryImages = [
    { src: './1.png', alt: 'Image 1'},
    { src: './2.png', alt: 'Image 2'},
    { src: './3.png', alt: 'Image 3'},
    { src: './4.png', alt: 'Image 4'},
    { src: './5.png', alt: 'Image 5'},
    { src: './6.png', alt: 'Image 6'},
    { src: './7.png', alt: 'Image 7'},
    { src: './8.png', alt: 'Image 8'},
    { src: './9.png', alt: 'Image 9'},
    { src: './10.png', alt: 'Image 10'},
    { src: './11.png', alt: 'Image 11'},
    { src: './12.png', alt: 'Image 12'},
    { src: './13.png', alt: 'Image 13'},
    { src: './14.png', alt: 'Image 14'},
    { src: './15.png', alt: 'Image 15'},
    { src: './16.png', alt: 'Image 16'},
    { src: './17.png', alt: 'Image 17'},
    { src: './18.png', alt: 'Image 18'},
    { src: './19.png', alt: 'Image 19'},
    { src: './20.png', alt: 'Image 20'},
    { src: './21.png', alt: 'Image 21'},
    { src: './22.png', alt: 'Image 22'},
    { src: './23.png', alt: 'Image 23'},
    { src: './24.png', alt: 'Image 24'},
    { src: './25.png', alt: 'Image 25'},
    { src: './26.png', alt: 'Image 26'},
    { src: './27.png', alt: 'Image 27'},
    { src: './28.png', alt: 'Image 28'},
    { src: './29.png', alt: 'Image 29'},
    { src: './30.png', alt: 'Image 30'},
    { src: './31.png', alt: 'Image 31'},
    { src: './32.png', alt: 'Image 32'},
    { src: './33.png', alt: 'Image 33'},
    { src: './34.png', alt: 'Image 34'},
    { src: './35.png', alt: 'Image 35'},
    { src: './36.png', alt: 'Image 36'},
    { src: './37.png', alt: 'Image 37'},
    { src: './38.png', alt: 'Image 38'},
    { src: './39.png', alt: 'Image 39'},
    { src: './40.png', alt: 'Image 40'},
    { src: './41.png', alt: 'Image 41'},
    { src: './42.png', alt: 'Image 42'},
    { src: './43.png', alt: 'Image 43'},
    { src: './44.png', alt: 'Image 44'},
    { src: './45.png', alt: 'Image 45'},
    { src: './46.png', alt: 'Image 46'},
    { src: './47.png', alt: 'Image 47'},
    { src: './48.png', alt: 'Image 48'},
    { src: './49.png', alt: 'Image 49'},
    { src: './50.png', alt: 'Image 50'},

];

export default galleryImages;